// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pfm_objective_cpp
double pfm_objective_cpp(const arma::vec& x, const arma::mat& X, double a);
RcppExport SEXP _PowerFrechetMeanR_pfm_objective_cpp(SEXP xSEXP, SEXP XSEXP, SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(pfm_objective_cpp(x, X, a));
    return rcpp_result_gen;
END_RCPP
}
// pfm_gradient_cpp
arma::vec pfm_gradient_cpp(const arma::vec& x, const arma::mat& X, double a, double eps);
RcppExport SEXP _PowerFrechetMeanR_pfm_gradient_cpp(SEXP xSEXP, SEXP XSEXP, SEXP aSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(pfm_gradient_cpp(x, X, a, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PowerFrechetMeanR_pfm_objective_cpp", (DL_FUNC) &_PowerFrechetMeanR_pfm_objective_cpp, 3},
    {"_PowerFrechetMeanR_pfm_gradient_cpp", (DL_FUNC) &_PowerFrechetMeanR_pfm_gradient_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PowerFrechetMeanR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
