# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pfm_objective_cpp <- function(x, X, a) {
    .Call(`_PowerFrechetMeanR_pfm_objective_cpp`, x, X, a)
}

pfm_gradient_cpp <- function(x, X, a, eps = 1e-10) {
    .Call(`_PowerFrechetMeanR_pfm_gradient_cpp`, x, X, a, eps)
}

